{"about": "", "activation_request_count": 0, "active": "0", 
"address": "", "admin": "0", "aff_balance": "0", "approved_at": 0, 
"avater": "Public/images/photos/2022/11/zV4cKhD54rETyFsBKSFp_full.png", 
"balance": "0.00", "birthday": "20", "body": 3, "book": "", "boosted_time": 0,
 "car": 0, "cc_phone_number": "", "character": 0, "children": 0, "city": "big ciry",
  "colour": "", "confirm_followers": "0", "country": "nigeria", "created_at": "2022-11-13 14:44:10", 
  "deleted_at": "2022-11-13 13:44:10", "dish": "", "drink": 0, "education": 0, "email": "den@gmail.com",
   "email_on_announcements": 0, "email_on_chat_request": 0, "email_on_get_gift": 0, "email_on_got_new_match": 0,
    "email_on_new_message": 0, "email_on_profile_like": 0, "email_on_profile_view": 0, "email_on_purchase_notifications": 0, 
    "email_on_special_offers": 0, "ethnicity": 0, "facebook": "", "first_name": "Tst",
     "friends": 0, "gender": "4525", "google": "", "hair_color": "", "height": "170", "hobby": "",
      "hot_count": 0, "id": 224, "info_file": "", "instagram": "", "interest": null, "ip_address": "102.89.44.69",
       "is_boosted": 0, "is_buy_stickers": 0, "is_pro": "0", "language": "english",
        "last_activation_request": 0, "last_email_sent": 0, "last_location_update": 0, "last_name": "Firstes", 
        "lastseen": 1668347050, "lat": "0", "likesCount": 0, "linkedin": "", "live_with": 0, "lng": "0",
         "location": "", "lock_private_photo": 1, "lock_pro_video": 1, "mobile_device": "", "mobile_device_id": "", 
         "mobile_token": "", "mobile_token_created_at": 0, "movie": "", "music": "", "new_email": "", "new_phone": "", 
         "online": 1, "paypal_email": "", "permission": null, "pets": 0, "phone_number": "9029292627", "phone_verified": 0, 
         "popularity": {"percent": "%0", "status": "Very Low", "value": 0}, "privacy_show_profile_match_profiles": 1,
          "privacy_show_profile_on_google": 0, "privacy_show_profile_random_users": 1, "pro_time": 0, "pro_type": "0", 
          "profileCompletionStatus": {"complete_level": "23.7/100", "complete_percent": "%23.7", "complete_value": 23.7, 
          "total_completed": 9, "total_to_complete": 38}, "referrer": 0, "registered": 1668347050, "relationship": 0,
           "religion": 3, "reward_daily_credit": 0, "show_me_to": "", "smoke": 0, "smscode": 529782, 
           "snapshot": "Public/images/photos/2022/11/Ca1xjfveqFnZwsCUYUNs_full.png", "social_login": "0",
            "song": "", "spam_warning": 0, "sport": "", "start_up": "3", "state": "kristin", "status": "3", 
            "timezone": "UTC", "travel": 0, "tv": "", "twitter": "", "two_factor": 0, "two_factor_email_code": "", 
            "two_factor_verified": 0, "updated_at": "2022-11-13 13:44:10", "user_buy_xlikes": 0, "user_buy_xmatches": 0, 
            "user_buy_xvisits": 0, "username": "BirTs", "verified": "0", "viewsCount": 0, "web_device": "", "web_device_id": "", "web_token": "", 
            "web_token_created_at": 0, "website": "", 
"work_status": 0, "xlikes_created_at": 0, "xmatches_created_at": 0, "xvisits_created_at": 0, "zip": 0}