//
export const Religion = [
  {key: 1, value: 'Muslim'},
  {key: 2, value: 'Atheists'},
  {key: 3, value: 'Buddhist'},
  {key: 4, value: 'Catholic'},
  {key: 5, value: 'Christain'},
  {key: 6, value: 'Hindu'},
  {key: 7, value: 'Jewish'},
  {key: 8, value: 'Agnostic'},
  {key: 9, value: 'Sikh'},
  {key: 10, value: 'Othes'},
];

export const Gender = [
  {key: 4525, value: 'Male'},
  {key: 4526, value: 'Female'},
  {key: 4527, value: 'Others'},
];

export const Statuss = [
  {key: 1, value: 'Single'},
  {key: 2, value: 'Married'},
];

// ethnicity

export const ethnicityy = [
  {key: 1, value: 'White'},
  {key: 2, value: 'Black'},
  {key: 3, value: 'Middle Eastern'},
  {key: 4, value: 'North African'},
  {key: 6, value: 'Mixed'},
  {key: 7, value: 'Asian'},
  {key: 8, value: 'Others'},
];

export const educations = [
  {key: 1, value: 'Secondary School'},
  {key: 2, value: 'iti'},
  {key: 3, value: 'College'},
  {key: 4, value: 'ther Education'},
];

export const country = [
  {
    name: 'Afghanistan',
    id: 1,
    flag: '🇦🇫',
    emojiU: 'U+1F1E6 U+1F1EB',
  },
  {
    name: 'Aland Islands',
    id: 2,
    flag: '🇦🇽',
    emojiU: 'U+1F1E6 U+1F1FD',
  },
  {
    name: 'Albania',
    id: 3,
    flag: '🇦🇱',
    emojiU: 'U+1F1E6 U+1F1F1',
  },
  {
    name: 'Algeria',
    id: 4,
    flag: '🇩🇿',
    emojiU: 'U+1F1E9 U+1F1FF',
  },
  {
    name: 'American Samoa',
    id: 5,
    flag: '🇦🇸',
    emojiU: 'U+1F1E6 U+1F1F8',
  },
  {
    name: 'Andorra',
    id: 6,
    flag: '🇦🇩',
    emojiU: 'U+1F1E6 U+1F1E9',
  },
  {
    name: 'Angola',
    id: 7,
    flag: '🇦🇴',
    emojiU: 'U+1F1E6 U+1F1F4',
  },
  {
    name: 'Anguilla',
    id: 8,
    flag: '🇦🇮',
    emojiU: 'U+1F1E6 U+1F1EE',
  },
  {
    name: 'Antarctica',
    id: 9,
    flag: '🇦🇶',
    emojiU: 'U+1F1E6 U+1F1F6',
  },
  {
    name: 'Antigua And Barbuda',
    id: 10,
    flag: '🇦🇬',
    emojiU: 'U+1F1E6 U+1F1EC',
  },
  {
    name: 'Argentina',
    id: 11,
    flag: '🇦🇷',
    emojiU: 'U+1F1E6 U+1F1F7',
  },
  {
    name: 'Armenia',
    id: 12,
    flag: '🇦🇲',
    emojiU: 'U+1F1E6 U+1F1F2',
  },
  {
    name: 'Aruba',
    id: 13,
    flag: '🇦🇼',
    emojiU: 'U+1F1E6 U+1F1FC',
  },
  {
    name: 'Australia',
    id: 14,
    flag: '🇦🇺',
    emojiU: 'U+1F1E6 U+1F1FA',
  },
  {
    name: 'Austria',
    id: 15,
    flag: '🇦🇹',
    emojiU: 'U+1F1E6 U+1F1F9',
  },
  {
    name: 'Azerbaijan',
    id: 16,
    flag: '🇦🇿',
    emojiU: 'U+1F1E6 U+1F1FF',
  },
  {
    name: 'Bahamas The',
    id: 17,
    flag: '🇧🇸',
    emojiU: 'U+1F1E7 U+1F1F8',
  },
  {
    name: 'Bahrain',
    id: 18,
    flag: '🇧🇭',
    emojiU: 'U+1F1E7 U+1F1ED',
  },
  {
    name: 'Bangladesh',
    id: 19,
    flag: '🇧🇩',
    emojiU: 'U+1F1E7 U+1F1E9',
  },
  {
    name: 'Barbados',
    id: 20,
    flag: '🇧🇧',
    emojiU: 'U+1F1E7 U+1F1E7',
  },
  {
    name: 'Belarus',
    id: 21,
    flag: '🇧🇾',
    emojiU: 'U+1F1E7 U+1F1FE',
  },
  {
    name: 'Belgium',
    id: 22,
    flag: '🇧🇪',
    emojiU: 'U+1F1E7 U+1F1EA',
  },
  {
    name: 'Belize',
    id: 23,
    flag: '🇧🇿',
    emojiU: 'U+1F1E7 U+1F1FF',
  },
  {
    name: 'Benin',
    id: 24,
    flag: '🇧🇯',
    emojiU: 'U+1F1E7 U+1F1EF',
  },
  {
    name: 'Bermuda',
    id: 25,
    flag: '🇧🇲',
    emojiU: 'U+1F1E7 U+1F1F2',
  },
  {
    name: 'Bhutan',
    id: 26,
    flag: '🇧🇹',
    emojiU: 'U+1F1E7 U+1F1F9',
  },
  {
    name: 'Bolivia',
    id: 27,
    flag: '🇧🇴',
    emojiU: 'U+1F1E7 U+1F1F4',
  },
  {
    name: 'Bosnia and Herzegovina',
    id: 28,
    flag: '🇧🇦',
    emojiU: 'U+1F1E7 U+1F1E6',
  },
  {
    name: 'Botswana',
    id: 29,
    flag: '🇧🇼',
    emojiU: 'U+1F1E7 U+1F1FC',
  },
  {
    name: 'Bouvet Island',
    id: 30,
    flag: '🇧🇻',
    emojiU: 'U+1F1E7 U+1F1FB',
  },
  {
    name: 'Brazil',
    id: 31,
    flag: '🇧🇷',
    emojiU: 'U+1F1E7 U+1F1F7',
  },
  {
    name: 'British Indian Ocean Territory',
    id: 32,
    flag: '🇮🇴',
    emojiU: 'U+1F1EE U+1F1F4',
  },
  {
    name: 'Brunei',
    id: 33,
    flag: '🇧🇳',
    emojiU: 'U+1F1E7 U+1F1F3',
  },
  {
    name: 'Bulgaria',
    id: 34,
    flag: '🇧🇬',
    emojiU: 'U+1F1E7 U+1F1EC',
  },
  {
    name: 'Burkina Faso',
    id: 35,
    flag: '🇧🇫',
    emojiU: 'U+1F1E7 U+1F1EB',
  },
  {
    name: 'Burundi',
    id: 36,
    flag: '🇧🇮',
    emojiU: 'U+1F1E7 U+1F1EE',
  },
  {
    name: 'Cambodia',
    id: 37,
    flag: '🇰🇭',
    emojiU: 'U+1F1F0 U+1F1ED',
  },
  {
    name: 'Cameroon',
    id: 38,
    flag: '🇨🇲',
    emojiU: 'U+1F1E8 U+1F1F2',
  },
  {
    name: 'Canada',
    id: 39,
    flag: '🇨🇦',
    emojiU: 'U+1F1E8 U+1F1E6',
  },
  {
    name: 'Cape Verde',
    id: 40,
    flag: '🇨🇻',
    emojiU: 'U+1F1E8 U+1F1FB',
  },
  {
    name: 'Cayman Islands',
    id: 41,
    flag: '🇰🇾',
    emojiU: 'U+1F1F0 U+1F1FE',
  },
  {
    name: 'Central African Republic',
    id: 42,
    flag: '🇨🇫',
    emojiU: 'U+1F1E8 U+1F1EB',
  },
  {
    name: 'Chad',
    id: 43,
    flag: '🇹🇩',
    emojiU: 'U+1F1F9 U+1F1E9',
  },
  {
    name: 'Chile',
    id: 44,
    flag: '🇨🇱',
    emojiU: 'U+1F1E8 U+1F1F1',
  },
  {
    name: 'China',
    id: 45,
    flag: '🇨🇳',
    emojiU: 'U+1F1E8 U+1F1F3',
  },
  {
    name: 'Christmas Island',
    id: 46,
    flag: '🇨🇽',
    emojiU: 'U+1F1E8 U+1F1FD',
  },
  {
    name: 'Cocos (Keeling) Islands',
    id: 47,
    flag: '🇨🇨',
    emojiU: 'U+1F1E8 U+1F1E8',
  },
  {
    name: 'Colombia',
    id: 48,
    flag: '🇨🇴',
    emojiU: 'U+1F1E8 U+1F1F4',
  },
  {
    name: 'Comoros',
    id: 49,
    flag: '🇰🇲',
    emojiU: 'U+1F1F0 U+1F1F2',
  },
  {
    name: 'Congo',
    id: 50,
    flag: '🇨🇬',
    emojiU: 'U+1F1E8 U+1F1EC',
  },
  {
    name: 'Congo The Democratic Republic Of The',
    id: 51,
    flag: '🇨🇩',
    emojiU: 'U+1F1E8 U+1F1E9',
  },
  {
    name: 'Cook Islands',
    id: 52,
    flag: '🇨🇰',
    emojiU: 'U+1F1E8 U+1F1F0',
  },
  {
    name: 'Costa Rica',
    id: 53,
    flag: '🇨🇷',
    emojiU: 'U+1F1E8 U+1F1F7',
  },
  {
    name: "Cote D'Ivoire (Ivory Coast)",
    id: 54,
    flag: '🇨🇮',
    emojiU: 'U+1F1E8 U+1F1EE',
  },
  {
    name: 'Croatia (Hrvatska)',
    id: 55,
    flag: '🇭🇷',
    emojiU: 'U+1F1ED U+1F1F7',
  },
  {
    name: 'Cuba',
    id: 56,
    flag: '🇨🇺',
    emojiU: 'U+1F1E8 U+1F1FA',
  },
  {
    name: 'Cyprus',
    id: 57,
    flag: '🇨🇾',
    emojiU: 'U+1F1E8 U+1F1FE',
  },
  {
    name: 'Czech Republic',
    id: 58,
    flag: '🇨🇿',
    emojiU: 'U+1F1E8 U+1F1FF',
  },
  {
    name: 'Denmark',
    id: 59,
    flag: '🇩🇰',
    emojiU: 'U+1F1E9 U+1F1F0',
  },
  {
    name: 'Djibouti',
    id: 60,
    flag: '🇩🇯',
    emojiU: 'U+1F1E9 U+1F1EF',
  },
  {
    name: 'Dominica',
    id: 61,
    flag: '🇩🇲',
    emojiU: 'U+1F1E9 U+1F1F2',
  },
  {
    name: 'Dominican Republic',
    id: 62,
    flag: '🇩🇴',
    emojiU: 'U+1F1E9 U+1F1F4',
  },
  {
    name: 'East Timor',
    id: 63,
    flag: '🇹🇱',
    emojiU: 'U+1F1F9 U+1F1F1',
  },
  {
    name: 'Ecuador',
    id: 64,
    flag: '🇪🇨',
    emojiU: 'U+1F1EA U+1F1E8',
  },
  {
    name: 'Egypt',
    id: 65,
    flag: '🇪🇬',
    emojiU: 'U+1F1EA U+1F1EC',
  },
  {
    name: 'El Salvador',
    id: 66,
    flag: '🇸🇻',
    emojiU: 'U+1F1F8 U+1F1FB',
  },
  {
    name: 'Equatorial Guinea',
    id: 67,
    flag: '🇬🇶',
    emojiU: 'U+1F1EC U+1F1F6',
  },
  {
    name: 'Eritrea',
    id: 68,
    flag: '🇪🇷',
    emojiU: 'U+1F1EA U+1F1F7',
  },
  {
    name: 'Estonia',
    id: 69,
    flag: '🇪🇪',
    emojiU: 'U+1F1EA U+1F1EA',
  },
  {
    name: 'Ethiopia',
    id: 70,
    flag: '🇪🇹',
    emojiU: 'U+1F1EA U+1F1F9',
  },
  {
    name: 'Falkland Islands',
    id: 71,
    flag: '🇫🇰',
    emojiU: 'U+1F1EB U+1F1F0',
  },
  {
    name: 'Faroe Islands',
    id: 72,
    flag: '🇫🇴',
    emojiU: 'U+1F1EB U+1F1F4',
  },
  {
    name: 'Fiji Islands',
    id: 73,
    flag: '🇫🇯',
    emojiU: 'U+1F1EB U+1F1EF',
  },
  {
    name: 'Finland',
    id: 74,
    flag: '🇫🇮',
    emojiU: 'U+1F1EB U+1F1EE',
  },
  {
    name: 'France',
    id: 75,
    flag: '🇫🇷',
    emojiU: 'U+1F1EB U+1F1F7',
  },
  {
    name: 'French Guiana',
    id: 76,
    flag: '🇬🇫',
    emojiU: 'U+1F1EC U+1F1EB',
  },
  {
    name: 'French Polynesia',
    id: 77,
    flag: '🇵🇫',
    emojiU: 'U+1F1F5 U+1F1EB',
  },
  {
    name: 'French Southern Territories',
    id: 78,
    flag: '🇹🇫',
    emojiU: 'U+1F1F9 U+1F1EB',
  },
  {
    name: 'Gabon',
    id: 79,
    flag: '🇬🇦',
    emojiU: 'U+1F1EC U+1F1E6',
  },
  {
    name: 'Gambia The',
    id: 80,
    flag: '🇬🇲',
    emojiU: 'U+1F1EC U+1F1F2',
  },
  {
    name: 'Georgia',
    id: 81,
    flag: '🇬🇪',
    emojiU: 'U+1F1EC U+1F1EA',
  },
  {
    name: 'Germany',
    id: 82,
    flag: '🇩🇪',
    emojiU: 'U+1F1E9 U+1F1EA',
  },
  {
    name: 'Ghana',
    id: 83,
    flag: '🇬🇭',
    emojiU: 'U+1F1EC U+1F1ED',
  },
  {
    name: 'Gibraltar',
    id: 84,
    flag: '🇬🇮',
    emojiU: 'U+1F1EC U+1F1EE',
  },
  {
    name: 'Greece',
    id: 85,
    flag: '🇬🇷',
    emojiU: 'U+1F1EC U+1F1F7',
  },
  {
    name: 'Greenland',
    id: 86,
    flag: '🇬🇱',
    emojiU: 'U+1F1EC U+1F1F1',
  },
  {
    name: 'Grenada',
    id: 87,
    flag: '🇬🇩',
    emojiU: 'U+1F1EC U+1F1E9',
  },
  {
    name: 'Guadeloupe',
    id: 88,
    flag: '🇬🇵',
    emojiU: 'U+1F1EC U+1F1F5',
  },
  {
    name: 'Guam',
    id: 89,
    flag: '🇬🇺',
    emojiU: 'U+1F1EC U+1F1FA',
  },
  {
    name: 'Guatemala',
    id: 90,
    flag: '🇬🇹',
    emojiU: 'U+1F1EC U+1F1F9',
  },
  {
    name: 'Guernsey and Alderney',
    id: 91,
    flag: '🇬🇬',
    emojiU: 'U+1F1EC U+1F1EC',
  },
  {
    name: 'Guinea',
    id: 92,
    flag: '🇬🇳',
    emojiU: 'U+1F1EC U+1F1F3',
  },
  {
    name: 'Guinea-Bissau',
    id: 93,
    flag: '🇬🇼',
    emojiU: 'U+1F1EC U+1F1FC',
  },
  {
    name: 'Guyana',
    id: 94,
    flag: '🇬🇾',
    emojiU: 'U+1F1EC U+1F1FE',
  },
  {
    name: 'Haiti',
    id: 95,
    flag: '🇭🇹',
    emojiU: 'U+1F1ED U+1F1F9',
  },
  {
    name: 'Heard Island and McDonald Islands',
    id: 96,
    flag: '🇭🇲',
    emojiU: 'U+1F1ED U+1F1F2',
  },
  {
    name: 'Honduras',
    id: 97,
    flag: '🇭🇳',
    emojiU: 'U+1F1ED U+1F1F3',
  },
  {
    name: 'Hong Kong S.A.R.',
    id: 98,
    flag: '🇭🇰',
    emojiU: 'U+1F1ED U+1F1F0',
  },
  {
    name: 'Hungary',
    id: 99,
    flag: '🇭🇺',
    emojiU: 'U+1F1ED U+1F1FA',
  },
  {
    name: 'Iceland',
    id: 100,
    flag: '🇮🇸',
    emojiU: 'U+1F1EE U+1F1F8',
  },
  {
    name: 'India',
    id: 101,
    flag: '🇮🇳',
    emojiU: 'U+1F1EE U+1F1F3',
  },
  {
    name: 'Indonesia',
    id: 102,
    flag: '🇮🇩',
    emojiU: 'U+1F1EE U+1F1E9',
  },
  {
    name: 'Iran',
    id: 103,
    flag: '🇮🇷',
    emojiU: 'U+1F1EE U+1F1F7',
  },
  {
    name: 'Iraq',
    id: 104,
    flag: '🇮🇶',
    emojiU: 'U+1F1EE U+1F1F6',
  },
  {
    name: 'Ireland',
    id: 105,
    flag: '🇮🇪',
    emojiU: 'U+1F1EE U+1F1EA',
  },
  {
    name: 'Israel',
    id: 106,
    flag: '🇮🇱',
    emojiU: 'U+1F1EE U+1F1F1',
  },
  {
    name: 'Italy',
    id: 107,
    flag: '🇮🇹',
    emojiU: 'U+1F1EE U+1F1F9',
  },
  {
    name: 'Jamaica',
    id: 108,
    flag: '🇯🇲',
    emojiU: 'U+1F1EF U+1F1F2',
  },
  {
    name: 'Japan',
    id: 109,
    flag: '🇯🇵',
    emojiU: 'U+1F1EF U+1F1F5',
  },
  {
    name: 'Jersey',
    id: 110,
    flag: '🇯🇪',
    emojiU: 'U+1F1EF U+1F1EA',
  },
  {
    name: 'Jordan',
    id: 111,
    flag: '🇯🇴',
    emojiU: 'U+1F1EF U+1F1F4',
  },
  {
    name: 'Kazakhstan',
    id: 112,
    flag: '🇰🇿',
    emojiU: 'U+1F1F0 U+1F1FF',
  },
  {
    name: 'Kenya',
    id: 113,
    flag: '🇰🇪',
    emojiU: 'U+1F1F0 U+1F1EA',
  },
  {
    name: 'Kiribati',
    id: 114,
    flag: '🇰🇮',
    emojiU: 'U+1F1F0 U+1F1EE',
  },
  {
    name: 'Korea North',
    id: 115,
    flag: '🇰🇵',
    emojiU: 'U+1F1F0 U+1F1F5',
  },
  {
    name: 'Korea South',
    id: 116,
    flag: '🇰🇷',
    emojiU: 'U+1F1F0 U+1F1F7',
  },
  {
    name: 'Kuwait',
    id: 117,
    flag: '🇰🇼',
    emojiU: 'U+1F1F0 U+1F1FC',
  },
  {
    name: 'Kyrgyzstan',
    id: 118,
    flag: '🇰🇬',
    emojiU: 'U+1F1F0 U+1F1EC',
  },
  {
    name: 'Laos',
    id: 119,
    flag: '🇱🇦',
    emojiU: 'U+1F1F1 U+1F1E6',
  },
  {
    name: 'Latvia',
    id: 120,
    flag: '🇱🇻',
    emojiU: 'U+1F1F1 U+1F1FB',
  },
  {
    name: 'Lebanon',
    id: 121,
    flag: '🇱🇧',
    emojiU: 'U+1F1F1 U+1F1E7',
  },
  {
    name: 'Lesotho',
    id: 122,
    flag: '🇱🇸',
    emojiU: 'U+1F1F1 U+1F1F8',
  },
  {
    name: 'Liberia',
    id: 123,
    flag: '🇱🇷',
    emojiU: 'U+1F1F1 U+1F1F7',
  },
  {
    name: 'Libya',
    id: 124,
    flag: '🇱🇾',
    emojiU: 'U+1F1F1 U+1F1FE',
  },
  {
    name: 'Liechtenstein',
    id: 125,
    flag: '🇱🇮',
    emojiU: 'U+1F1F1 U+1F1EE',
  },
  {
    name: 'Lithuania',
    id: 126,
    flag: '🇱🇹',
    emojiU: 'U+1F1F1 U+1F1F9',
  },
  {
    name: 'Luxembourg',
    id: 127,
    flag: '🇱🇺',
    emojiU: 'U+1F1F1 U+1F1FA',
  },
  {
    name: 'Macau S.A.R.',
    id: 128,
    flag: '🇲🇴',
    emojiU: 'U+1F1F2 U+1F1F4',
  },
  {
    name: 'Macedonia',
    id: 129,
    flag: '🇲🇰',
    emojiU: 'U+1F1F2 U+1F1F0',
  },
  {
    name: 'Madagascar',
    id: 130,
    flag: '🇲🇬',
    emojiU: 'U+1F1F2 U+1F1EC',
  },
  {
    name: 'Malawi',
    id: 131,
    flag: '🇲🇼',
    emojiU: 'U+1F1F2 U+1F1FC',
  },
  {
    name: 'Malaysia',
    id: 132,
    flag: '🇲🇾',
    emojiU: 'U+1F1F2 U+1F1FE',
  },
  {
    name: 'Maldives',
    id: 133,
    flag: '🇲🇻',
    emojiU: 'U+1F1F2 U+1F1FB',
  },
  {
    name: 'Mali',
    id: 134,
    flag: '🇲🇱',
    emojiU: 'U+1F1F2 U+1F1F1',
  },
  {
    name: 'Malta',
    id: 135,
    flag: '🇲🇹',
    emojiU: 'U+1F1F2 U+1F1F9',
  },
  {
    name: 'Man (Isle of)',
    id: 136,
    flag: '🇮🇲',
    emojiU: 'U+1F1EE U+1F1F2',
  },
  {
    name: 'Marshall Islands',
    id: 137,
    flag: '🇲🇭',
    emojiU: 'U+1F1F2 U+1F1ED',
  },
  {
    name: 'Martinique',
    id: 138,
    flag: '🇲🇶',
    emojiU: 'U+1F1F2 U+1F1F6',
  },
  {
    name: 'Mauritania',
    id: 139,
    flag: '🇲🇷',
    emojiU: 'U+1F1F2 U+1F1F7',
  },
  {
    name: 'Mauritius',
    id: 140,
    flag: '🇲🇺',
    emojiU: 'U+1F1F2 U+1F1FA',
  },
  {
    name: 'Mayotte',
    id: 141,
    flag: '🇾🇹',
    emojiU: 'U+1F1FE U+1F1F9',
  },
  {
    name: 'Mexico',
    id: 142,
    flag: '🇲🇽',
    emojiU: 'U+1F1F2 U+1F1FD',
  },
  {
    name: 'Micronesia',
    id: 143,
    flag: '🇫🇲',
    emojiU: 'U+1F1EB U+1F1F2',
  },
  {
    name: 'Moldova',
    id: 144,
    flag: '🇲🇩',
    emojiU: 'U+1F1F2 U+1F1E9',
  },
  {
    name: 'Monaco',
    id: 145,
    flag: '🇲🇨',
    emojiU: 'U+1F1F2 U+1F1E8',
  },
  {
    name: 'Mongolia',
    id: 146,
    flag: '🇲🇳',
    emojiU: 'U+1F1F2 U+1F1F3',
  },
  {
    name: 'Montenegro',
    id: 147,
    flag: '🇲🇪',
    emojiU: 'U+1F1F2 U+1F1EA',
  },
  {
    name: 'Montserrat',
    id: 148,
    flag: '🇲🇸',
    emojiU: 'U+1F1F2 U+1F1F8',
  },
  {
    name: 'Morocco',
    id: 149,
    flag: '🇲🇦',
    emojiU: 'U+1F1F2 U+1F1E6',
  },
  {
    name: 'Mozambique',
    id: 150,
    flag: '🇲🇿',
    emojiU: 'U+1F1F2 U+1F1FF',
  },
  {
    name: 'Myanmar',
    id: 151,
    flag: '🇲🇲',
    emojiU: 'U+1F1F2 U+1F1F2',
  },
  {
    name: 'Namibia',
    id: 152,
    flag: '🇳🇦',
    emojiU: 'U+1F1F3 U+1F1E6',
  },
  {
    name: 'Nauru',
    id: 153,
    flag: '🇳🇷',
    emojiU: 'U+1F1F3 U+1F1F7',
  },
  {
    name: 'Nepal',
    id: 154,
    flag: '🇳🇵',
    emojiU: 'U+1F1F3 U+1F1F5',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    id: 155,
    flag: '🇧🇶',
    emojiU: 'U+1F1E7 U+1F1F6',
  },
  {
    name: 'Netherlands The',
    id: 156,
    flag: '🇳🇱',
    emojiU: 'U+1F1F3 U+1F1F1',
  },
  {
    name: 'New Caledonia',
    id: 157,
    flag: '🇳🇨',
    emojiU: 'U+1F1F3 U+1F1E8',
  },
  {
    name: 'New Zealand',
    id: 158,
    flag: '🇳🇿',
    emojiU: 'U+1F1F3 U+1F1FF',
  },
  {
    name: 'Nicaragua',
    id: 159,
    flag: '🇳🇮',
    emojiU: 'U+1F1F3 U+1F1EE',
  },
  {
    name: 'Niger',
    id: 160,
    flag: '🇳🇪',
    emojiU: 'U+1F1F3 U+1F1EA',
  },
  {
    name: 'Nigeria',
    id: 161,
    flag: '🇳🇬',
    emojiU: 'U+1F1F3 U+1F1EC',
  },
  {
    name: 'Niue',
    id: 162,
    flag: '🇳🇺',
    emojiU: 'U+1F1F3 U+1F1FA',
  },
  {
    name: 'Norfolk Island',
    id: 163,
    flag: '🇳🇫',
    emojiU: 'U+1F1F3 U+1F1EB',
  },
  {
    name: 'Northern Mariana Islands',
    id: 164,
    flag: '🇲🇵',
    emojiU: 'U+1F1F2 U+1F1F5',
  },
  {
    name: 'Norway',
    id: 165,
    flag: '🇳🇴',
    emojiU: 'U+1F1F3 U+1F1F4',
  },
  {
    name: 'Oman',
    id: 166,
    flag: '🇴🇲',
    emojiU: 'U+1F1F4 U+1F1F2',
  },
  {
    name: 'Pakistan',
    id: 167,
    flag: '🇵🇰',
    emojiU: 'U+1F1F5 U+1F1F0',
  },
  {
    name: 'Palau',
    id: 168,
    flag: '🇵🇼',
    emojiU: 'U+1F1F5 U+1F1FC',
  },
  {
    name: 'Palestinian Territory Occupied',
    id: 169,
    flag: '🇵🇸',
    emojiU: 'U+1F1F5 U+1F1F8',
  },
  {
    name: 'Panama',
    id: 170,
    flag: '🇵🇦',
    emojiU: 'U+1F1F5 U+1F1E6',
  },
  {
    name: 'Papua new Guinea',
    id: 171,
    flag: '🇵🇬',
    emojiU: 'U+1F1F5 U+1F1EC',
  },
  {
    name: 'Paraguay',
    id: 172,
    flag: '🇵🇾',
    emojiU: 'U+1F1F5 U+1F1FE',
  },
  {
    name: 'Peru',
    id: 173,
    flag: '🇵🇪',
    emojiU: 'U+1F1F5 U+1F1EA',
  },
  {
    name: 'Philippines',
    id: 174,
    flag: '🇵🇭',
    emojiU: 'U+1F1F5 U+1F1ED',
  },
  {
    name: 'Pitcairn Island',
    id: 175,
    flag: '🇵🇳',
    emojiU: 'U+1F1F5 U+1F1F3',
  },
  {
    name: 'Poland',
    id: 176,
    flag: '🇵🇱',
    emojiU: 'U+1F1F5 U+1F1F1',
  },
  {
    name: 'Portugal',
    id: 177,
    flag: '🇵🇹',
    emojiU: 'U+1F1F5 U+1F1F9',
  },
  {
    name: 'Puerto Rico',
    id: 178,
    flag: '🇵🇷',
    emojiU: 'U+1F1F5 U+1F1F7',
  },
  {
    name: 'Qatar',
    id: 179,
    flag: '🇶🇦',
    emojiU: 'U+1F1F6 U+1F1E6',
  },
  {
    name: 'Reunion',
    id: 180,
    flag: '🇷🇪',
    emojiU: 'U+1F1F7 U+1F1EA',
  },
  {
    name: 'Romania',
    id: 181,
    flag: '🇷🇴',
    emojiU: 'U+1F1F7 U+1F1F4',
  },
  {
    name: 'Russia',
    id: 182,
    flag: '🇷🇺',
    emojiU: 'U+1F1F7 U+1F1FA',
  },
  {
    name: 'Rwanda',
    id: 183,
    flag: '🇷🇼',
    emojiU: 'U+1F1F7 U+1F1FC',
  },
  {
    name: 'Saint Helena',
    id: 184,
    flag: '🇸🇭',
    emojiU: 'U+1F1F8 U+1F1ED',
  },
  {
    name: 'Saint Kitts And Nevis',
    id: 185,
    flag: '🇰🇳',
    emojiU: 'U+1F1F0 U+1F1F3',
  },
  {
    name: 'Saint Lucia',
    id: 186,
    flag: '🇱🇨',
    emojiU: 'U+1F1F1 U+1F1E8',
  },
  {
    name: 'Saint Pierre and Miquelon',
    id: 187,
    flag: '🇵🇲',
    emojiU: 'U+1F1F5 U+1F1F2',
  },
  {
    name: 'Saint Vincent And The Grenadines',
    id: 188,
    flag: '🇻🇨',
    emojiU: 'U+1F1FB U+1F1E8',
  },
  {
    name: 'Saint-Barthelemy',
    id: 189,
    flag: '🇧🇱',
    emojiU: 'U+1F1E7 U+1F1F1',
  },
  {
    name: 'Saint-Martin (French part)',
    id: 190,
    flag: '🇲🇫',
    emojiU: 'U+1F1F2 U+1F1EB',
  },
  {
    name: 'Samoa',
    id: 191,
    flag: '🇼🇸',
    emojiU: 'U+1F1FC U+1F1F8',
  },
  {
    name: 'San Marino',
    id: 192,
    flag: '🇸🇲',
    emojiU: 'U+1F1F8 U+1F1F2',
  },
  {
    name: 'Sao Tome and Principe',
    id: 193,
    flag: '🇸🇹',
    emojiU: 'U+1F1F8 U+1F1F9',
  },
  {
    name: 'Saudi Arabia',
    id: 194,
    flag: '🇸🇦',
    emojiU: 'U+1F1F8 U+1F1E6',
  },
  {
    name: 'Senegal',
    id: 195,
    flag: '🇸🇳',
    emojiU: 'U+1F1F8 U+1F1F3',
  },
  {
    name: 'Serbia',
    id: 196,
    flag: '🇷🇸',
    emojiU: 'U+1F1F7 U+1F1F8',
  },
  {
    name: 'Seychelles',
    id: 197,
    flag: '🇸🇨',
    emojiU: 'U+1F1F8 U+1F1E8',
  },
  {
    name: 'Sierra Leone',
    id: 198,
    flag: '🇸🇱',
    emojiU: 'U+1F1F8 U+1F1F1',
  },
  {
    name: 'Singapore',
    id: 199,
    flag: '🇸🇬',
    emojiU: 'U+1F1F8 U+1F1EC',
  },
  {
    name: 'Slovakia',
    id: 200,
    flag: '🇸🇰',
    emojiU: 'U+1F1F8 U+1F1F0',
  },
  {
    name: 'Slovenia',
    id: 201,
    flag: '🇸🇮',
    emojiU: 'U+1F1F8 U+1F1EE',
  },
  {
    name: 'Solomon Islands',
    id: 202,
    flag: '🇸🇧',
    emojiU: 'U+1F1F8 U+1F1E7',
  },
  {
    name: 'Somalia',
    id: 203,
    flag: '🇸🇴',
    emojiU: 'U+1F1F8 U+1F1F4',
  },
  {
    name: 'South Africa',
    id: 204,
    flag: '🇿🇦',
    emojiU: 'U+1F1FF U+1F1E6',
  },
  {
    name: 'South Georgia',
    id: 205,
    flag: '🇬🇸',
    emojiU: 'U+1F1EC U+1F1F8',
  },
  {
    name: 'South Sudan',
    id: 206,
    flag: '🇸🇸',
    emojiU: 'U+1F1F8 U+1F1F8',
  },
  {
    name: 'Spain',
    id: 207,
    flag: '🇪🇸',
    emojiU: 'U+1F1EA U+1F1F8',
  },
  {
    name: 'Sri Lanka',
    id: 208,
    flag: '🇱🇰',
    emojiU: 'U+1F1F1 U+1F1F0',
  },
  {
    name: 'Sudan',
    id: 209,
    flag: '🇸🇩',
    emojiU: 'U+1F1F8 U+1F1E9',
  },
  {
    name: 'Suriname',
    id: 210,
    flag: '🇸🇷',
    emojiU: 'U+1F1F8 U+1F1F7',
  },
  {
    name: 'Svalbard And Jan Mayen Islands',
    id: 211,
    flag: '🇸🇯',
    emojiU: 'U+1F1F8 U+1F1EF',
  },
  {
    name: 'Swaziland',
    id: 212,
    flag: '🇸🇿',
    emojiU: 'U+1F1F8 U+1F1FF',
  },
  {
    name: 'Sweden',
    id: 213,
    flag: '🇸🇪',
    emojiU: 'U+1F1F8 U+1F1EA',
  },
  {
    name: 'Switzerland',
    id: 214,
    flag: '🇨🇭',
    emojiU: 'U+1F1E8 U+1F1ED',
  },
  {
    name: 'Syria',
    id: 215,
    flag: '🇸🇾',
    emojiU: 'U+1F1F8 U+1F1FE',
  },
  {
    name: 'Taiwan',
    id: 216,
    flag: '🇹🇼',
    emojiU: 'U+1F1F9 U+1F1FC',
  },
  {
    name: 'Tajikistan',
    id: 217,
    flag: '🇹🇯',
    emojiU: 'U+1F1F9 U+1F1EF',
  },
  {
    name: 'Tanzania',
    id: 218,
    flag: '🇹🇿',
    emojiU: 'U+1F1F9 U+1F1FF',
  },
  {
    name: 'Thailand',
    id: 219,
    flag: '🇹🇭',
    emojiU: 'U+1F1F9 U+1F1ED',
  },
  {
    name: 'Togo',
    id: 220,
    flag: '🇹🇬',
    emojiU: 'U+1F1F9 U+1F1EC',
  },
  {
    name: 'Tokelau',
    id: 221,
    flag: '🇹🇰',
    emojiU: 'U+1F1F9 U+1F1F0',
  },
  {
    name: 'Tonga',
    id: 222,
    flag: '🇹🇴',
    emojiU: 'U+1F1F9 U+1F1F4',
  },
  {
    name: 'Trinidad And Tobago',
    id: 223,
    flag: '🇹🇹',
    emojiU: 'U+1F1F9 U+1F1F9',
  },
  {
    name: 'Tunisia',
    id: 224,
    flag: '🇹🇳',
    emojiU: 'U+1F1F9 U+1F1F3',
  },
  {
    name: 'Turkey',
    id: 225,
    flag: '🇹🇷',
    emojiU: 'U+1F1F9 U+1F1F7',
  },
  {
    name: 'Turkmenistan',
    id: 226,
    flag: '🇹🇲',
    emojiU: 'U+1F1F9 U+1F1F2',
  },
  {
    name: 'Turks And Caicos Islands',
    id: 227,
    flag: '🇹🇨',
    emojiU: 'U+1F1F9 U+1F1E8',
  },
  {
    name: 'Tuvalu',
    id: 228,
    flag: '🇹🇻',
    emojiU: 'U+1F1F9 U+1F1FB',
  },
  {
    name: 'Uganda',
    id: 229,
    flag: '🇺🇬',
    emojiU: 'U+1F1FA U+1F1EC',
  },
  {
    name: 'Ukraine',
    id: 230,
    flag: '🇺🇦',
    emojiU: 'U+1F1FA U+1F1E6',
  },
  {
    name: 'United Arab Emirates',
    id: 231,
    flag: '🇦🇪',
    emojiU: 'U+1F1E6 U+1F1EA',
  },
  {
    name: 'United Kingdom',
    id: 232,
    flag: '🇬🇧',
    emojiU: 'U+1F1EC U+1F1E7',
  },
  {
    name: 'United States',
    id: 233,
    flag: '🇺🇸',
    emojiU: 'U+1F1FA U+1F1F8',
  },
  {
    name: 'United States Minor Outlying Islands',
    id: 234,
    flag: '🇺🇲',
    emojiU: 'U+1F1FA U+1F1F2',
  },
  {
    name: 'Uruguay',
    id: 235,
    flag: '🇺🇾',
    emojiU: 'U+1F1FA U+1F1FE',
  },
  {
    name: 'Uzbekistan',
    id: 236,
    flag: '🇺🇿',
    emojiU: 'U+1F1FA U+1F1FF',
  },
  {
    name: 'Vanuatu',
    id: 237,
    flag: '🇻🇺',
    emojiU: 'U+1F1FB U+1F1FA',
  },
  {
    name: 'Vatican City State (Holy See)',
    id: 238,
    flag: '🇻🇦',
    emojiU: 'U+1F1FB U+1F1E6',
  },
  {
    name: 'Venezuela',
    id: 239,
    flag: '🇻🇪',
    emojiU: 'U+1F1FB U+1F1EA',
  },
  {
    name: 'Vietnam',
    id: 240,
    flag: '🇻🇳',
    emojiU: 'U+1F1FB U+1F1F3',
  },
  {
    name: 'Virgin Islands (British)',
    id: 241,
    flag: '🇻🇬',
    emojiU: 'U+1F1FB U+1F1EC',
  },
  {
    name: 'Virgin Islands (US)',
    id: 242,
    flag: '🇻🇮',
    emojiU: 'U+1F1FB U+1F1EE',
  },
  {
    name: 'Wallis And Futuna Islands',
    id: 243,
    flag: '🇼🇫',
    emojiU: 'U+1F1FC U+1F1EB',
  },
  {
    name: 'Western Sahara',
    id: 244,
    flag: '🇪🇭',
    emojiU: 'U+1F1EA U+1F1ED',
  },
  {
    name: 'Yemen',
    id: 245,
    flag: '🇾🇪',
    emojiU: 'U+1F1FE U+1F1EA',
  },
  {
    name: 'Zambia',
    id: 246,
    flag: '🇿🇲',
    emojiU: 'U+1F1FF U+1F1F2',
  },
  {
    name: 'Zimbabwe',
    id: 247,
    flag: '🇿🇼',
    emojiU: 'U+1F1FF U+1F1FC',
  },
  {
    name: 'Kosovo',
    id: 248,
    flag: '🇽🇰',
    emojiU: 'U+1F1FD U+1F1F0',
  },
  {
    name: 'Curaçao',
    id: 249,
    flag: '🇨🇼',
    emojiU: 'U+1F1E8 U+1F1FC',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    id: 250,
    flag: '🇸🇽',
    emojiU: 'U+1F1F8 U+1F1FD',
  },
];
